In [4]:
#Dependencies and Setup 
import matplotlib.pyplot as plt
import pandas as pd 
import numpy as np 
import requests
import json 
import gmaps 
import os 

# Import API key
from api_key import g_key

In [8]:
#loading the csv that was exported in part 1 to a dataframe 
weather_file = 'City_Data.csv'

#reading the data in the csv 
weather_df = pd.read_csv(weather_file,encoding='utf-8')

#Creating the DataFrame 
weather_df = pd.DataFrame(weather_df)

#Displaying the DataFrame
weather_df

,City,Latitude,Longtitude,Max Temp,Humidity,Cloudiness,Wind Speed,Country,Date
0,Hobyo,5.35,48.53,81.21,78,46,12.95,SO,1604084870
1,Tasiilaq,65.61,-37.64,32.00,97,75,3.36,GL,1604084913
2,Rikitea,-23.12,-134.97,75.63,69,0,8.19,PF,1604085065
3,Whakatane,-37.96,176.99,63.00,83,100,1.99,NZ,1604085066
4,Cape Town,-33.93,18.42,60.01,62,0,23.04,ZA,1604084955
...,...,...,...,...,...,...,...,...,...
551,Bhubaneswar,20.23,85.83,73.40,78,20,5.86,IN,1604085172
552,Moose Factory,51.26,-80.61,28.40,58,1,10.29,CA,1604084957
553,Venice,27.10,-82.45,79.00,65,1,14.99,US,1604085066
554,Ossora,59.24,163.07,30.47,92,0,2.06,RU,1604085173
555,Kaeo,-35.10,173.78,64.00,96,88,7.00,NZ,1604084919